spring.application.name=account-api

spring.datasource.url=jdbc:h2:mem:account;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.h2.console.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
